### ISSUE TITLE
just a typo...

### ISSUE THREAD

**Issue by phdsg** [KieranPringle/CastleRocktronics#1]
reading the manual https://github.com/KieranPringle/CastleRocktronics/blob/master/docs/cubefader.md stumbled across this one: "## Overivew"

also wanted to be the first to say thanks for your modules.
nice work.

**Comment by KieranPringle** [comment]
Thanks for this!
 
Fixed in: https://github.com/KieranPringle/CastleRocktronics/commit/92228f4fc7a4dba403ec8f25da1b7db90530f3cb so closing
