### ISSUE TITLE
Archive root folder does not match slug

### ISSUE THREAD

**Issue by cschol** [KieranPringle/CastleRocktronics#2]
The root folder of the plugin archive does not match the slug:

Slug: `CastleRocktronics`
Folder: `CastleRocktronics-0.5.0`

[Rack community repo issue reference](https://github.com/VCVRack/community/issues/200)

**Comment by KieranPringle** [comment]
Thankyou for this @cschol the fix is handled in this PR in the Rack Community Repo:
https://github.com/VCVRack/community/pull/256
