### ISSUE TITLE
non issue, just question (new to github)

### ISSUE THREAD

**Issue by DuvielPympion** [KieranPringle/CastleRocktronics#4]
are you there same guy behind the Lunetta based site http://castlerocktronics.com/modular.html

If so I'm stoked your still doing music projects as that site kicked off my DIY adventure in making noise boxes etc. 

Just saying thanks, delete this or or whatever as I know its not protocol, I just tried every contact method on your old page to reach you.

**Comment by Atavic** [comment]
Definitely it appears to be him.

**Comment by KieranPringle** [comment]
I am indeed, thanks for the kind words! I'm hoping to reboot the site a bit towards the end of this year. I went through a move from China to the UK and haven't been able to unpack any of my stuff or set up a workspace for two years but I'm going to be moving to somewhere with space in a few months.

Sorry about the lack of contact! I actually lost access to the email account, and have just forgotten (for two years) to get it set back up.

**Comment by DuvielPympion** [comment]
I loved the simple instructions plus the in-depth descriptions. That sight
is great. Maybe a filter or lfo not based on square waves next?

Anyway thanks for the resource!
