### ISSUE TITLE
Updates for VCV 1.0

### ISSUE THREAD

**Issue by rsmus7** [KieranPringle/CastleRocktronics#5]
any idea to update the modules for VCV 1.0?

I would like the cube very much

**Comment by KieranPringle** [comment]
Hey there. I've actually been trying to move my free time around enough to try porting this (and even do new modules!) since 1.0 is out and stable. It is slow going though, so I can't make any promises but thanks for the request! It gives me a bit more motivation to try and get back into it.

**Comment by rsmus7** [comment]
that's good news 
maybe this thread in the VCV forum can help:
https://community.vcvrack.com/t/plugin-authors-help-migrating-existing-plugins-to-rack-v1/3463

**Comment by KieranPringle** [comment]
Going to close this one just to keep things clean. Have started to make an attempt at this
